CREATE TABLE `Classes` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`_index` text,
	`_id` text,
	`_score` text,
	`_source_id_btbmi` integer,
	`_source_hs_code` text,
	`_source_uraian_en` text,
	`_source_uraian_id` text,
	`_source_timestamp` text,
	`_source_version` text,
	`_source_hs_code_format` text,
	`_source_bm_mfn` text,
	`_sort` text,
	`mfn_regulation` text,
	`mfn_issued_at` text,
	`mfn_effective_at` text,
	`mfn_bm` text,
	`mfn_ppn` text,
	`mfn_ppnbm` text,
	`mfn_cukai` text,
	`mfn_ad` text,
	`mfn_tp` text,
	`mfn_im` text,
	`mfn_pm` text,
	`mfn_pph` text,
	`mfn_ppnbk` text,
	`mfn_tarif_dana_sawit` text,
	`mfn_notes` text,
	`mfn_flag_sd` text
);
